import * as admin from 'firebase-admin';

// Initialize Firebase Admin SDK if not already active
if (admin.apps.length === 0) {
  admin.initializeApp();
}

const db = admin.firestore();
const auth = admin.auth();

// Seed data from Section 8 of API Contract & Data Model v1.0.0
export const SEED_DATA = {
  demoAccounts: [
    { uid: 'usr_student_01', email: 'nimasha@ucl.demo', role: 'student', displayName: 'Nimasha Perera', faculty: 'FOC', programme: 'BSC-SE', yearGroup: 2 },
    { uid: 'usr_student_02', email: 'ravi@ucl.demo', role: 'student', displayName: 'Ravi Kumar', faculty: 'FOB', programme: 'BBA', yearGroup: 1 },
    { uid: 'usr_rep_01', email: 'robotics.rep@ucl.demo', role: 'society_rep', displayName: 'Tharindu Jayasuriya', faculty: 'FOE', programme: 'BENG-CE', yearGroup: 3 },
    { uid: 'usr_acad_01', email: 'kasun@ucl.demo', role: 'academic_staff', displayName: 'Dr. Kasun Silva', faculty: 'FOC', department: 'Faculty of Computing' },
    { uid: 'usr_fin_01', email: 'finance@ucl.demo', role: 'finance_staff', displayName: 'Dilini Perera', department: 'Finance Office' },
    { uid: 'usr_mgr_01', email: 'manager@ucl.demo', role: 'manager', displayName: 'Facilities Manager', department: 'Facilities & Operations' },
    { uid: 'usr_admin_01', email: 'admin@ucl.demo', role: 'admin', displayName: 'Registrar Office', department: 'Registrar' },
    { uid: 'usr_super_01', email: 'super@ucl.demo', role: 'super_admin', displayName: 'Chief Administrator', department: 'IT & Infrastructure' },
    { uid: 'usr_alum_01', email: 'alumni@ucl.demo', role: 'alumni', displayName: 'Past Graduate', alumniGradYear: 2023 },
  ],

  users: [
    {
      id: 'usr_student_01',
      email: 'nimasha@ucl.demo',
      displayName: 'Nimasha Perera',
      role: 'student',
      status: 'active',
      faculty: 'FOC',
      programme: 'BSC-SE',
      yearGroup: 2,
      studentId: 'UCL/24/0142',
      phone: '+94771234567',
      smsOptIn: true,
      societyIds: ['soc_robotics'],
      department: null,
      alumniGradYear: null,
      fcmTokens: [],
      notifPrefs: { push: true, categories: { announcement: true, event: true, booking: true, request: true, society: true } },
      lastLoginAt: '2026-09-19T04:10:00.000Z',
      createdAt: '2026-08-01T05:00:00.000Z',
    },
    {
      id: 'usr_acad_01',
      email: 'kasun@ucl.demo',
      displayName: 'Dr. Kasun Silva',
      role: 'academic_staff',
      status: 'active',
      faculty: 'FOC',
      programme: null,
      yearGroup: null,
      studentId: null,
      phone: '+94772223344',
      smsOptIn: true,
      societyIds: [],
      department: 'Faculty of Computing',
      alumniGradYear: null,
      fcmTokens: [],
      notifPrefs: { push: true, categories: {} },
      lastLoginAt: '2026-09-19T03:00:00.000Z',
      createdAt: '2026-07-15T05:00:00.000Z',
    },
    {
      id: 'usr_rep_01',
      email: 'robotics.rep@ucl.demo',
      displayName: 'Tharindu Jayasuriya',
      role: 'society_rep',
      status: 'active',
      faculty: 'FOE',
      programme: 'BENG-CE',
      yearGroup: 3,
      studentId: 'UCL/23/0311',
      phone: '+94775556677',
      smsOptIn: true,
      societyIds: ['soc_robotics'],
      department: null,
      alumniGradYear: null,
      fcmTokens: [],
      notifPrefs: { push: true, categories: {} },
      lastLoginAt: '2026-09-18T15:00:00.000Z',
      createdAt: '2026-08-01T05:00:00.000Z',
    },
    {
      id: 'usr_student_02',
      email: 'ravi@ucl.demo',
      displayName: 'Ravi Kumar',
      role: 'student',
      status: 'active',
      faculty: 'FOB',
      programme: 'BBA',
      yearGroup: 1,
      studentId: 'UCL/25/0088',
      phone: '+94773334455',
      smsOptIn: true,
      societyIds: [],
      department: null,
      alumniGradYear: null,
      fcmTokens: [],
      notifPrefs: { push: true, categories: {} },
      lastLoginAt: '2026-09-18T05:00:00.000Z',
      createdAt: '2026-08-10T05:00:00.000Z',
    },
    {
      id: 'usr_fin_01',
      email: 'finance@ucl.demo',
      displayName: 'Finance Office',
      role: 'finance_staff',
      status: 'active',
      faculty: null,
      programme: null,
      yearGroup: null,
      studentId: null,
      phone: '+94774445566',
      smsOptIn: true,
      societyIds: [],
      department: 'Finance Office',
      alumniGradYear: null,
      fcmTokens: [],
      notifPrefs: { push: true, categories: {} },
      lastLoginAt: '2026-09-19T02:00:00.000Z',
      createdAt: '2026-06-01T05:00:00.000Z',
    },
    {
      id: 'usr_mgr_01',
      email: 'manager@ucl.demo',
      displayName: 'Facilities Manager',
      role: 'manager',
      status: 'active',
      faculty: null,
      programme: null,
      yearGroup: null,
      studentId: null,
      phone: '+94776667788',
      smsOptIn: true,
      societyIds: [],
      department: 'Facilities & Operations',
      alumniGradYear: null,
      fcmTokens: [],
      notifPrefs: { push: true, categories: {} },
      lastLoginAt: '2026-09-19T01:00:00.000Z',
      createdAt: '2026-06-01T05:00:00.000Z',
    },
    {
      id: 'usr_admin_01',
      email: 'admin@ucl.demo',
      displayName: 'Registrar Office',
      role: 'admin',
      status: 'active',
      faculty: null,
      programme: null,
      yearGroup: null,
      studentId: null,
      phone: '+94778889900',
      smsOptIn: true,
      societyIds: [],
      department: 'Registrar',
      alumniGradYear: null,
      fcmTokens: [],
      notifPrefs: { push: true, categories: {} },
      lastLoginAt: '2026-09-19T01:30:00.000Z',
      createdAt: '2026-05-01T05:00:00.000Z',
    },
    {
      id: 'usr_super_01',
      email: 'super@ucl.demo',
      displayName: 'IT Super Administrator',
      role: 'super_admin',
      status: 'active',
      faculty: null,
      programme: null,
      yearGroup: null,
      studentId: null,
      phone: '+94779990011',
      smsOptIn: true,
      societyIds: [],
      department: 'IT',
      alumniGradYear: null,
      fcmTokens: [],
      notifPrefs: { push: true, categories: {} },
      lastLoginAt: '2026-09-19T00:00:00.000Z',
      createdAt: '2026-01-01T05:00:00.000Z',
    },
    {
      id: 'usr_alum_01',
      email: 'alumni@ucl.demo',
      displayName: 'Graduated Alumnus',
      role: 'alumni',
      status: 'active',
      faculty: 'FOC',
      programme: 'BSC-CS',
      yearGroup: null,
      studentId: 'UCL/20/0012',
      phone: '+94770001122',
      smsOptIn: true,
      societyIds: [],
      department: null,
      alumniGradYear: 2023,
      fcmTokens: [],
      notifPrefs: { push: true, categories: {} },
      lastLoginAt: '2026-09-10T05:00:00.000Z',
      createdAt: '2026-08-01T05:00:00.000Z',
    },
  ],

  contents: [
    {
      id: 'cnt_a1b2c3',
      type: 'announcement',
      category: 'academic',
      title: 'Database Systems lab moved to Lab 3',
      summary: 'From Monday, DB labs for Year 2 SE run in Lab 3.',
      body: '**Effective 21 Sep.** Labs for Year 2 Software Engineering move from Lab 1 to **Lab 3** (Block B, 2nd floor). Bring your student ID.',
      imageUrl: null,
      tags: ['db', 'lab'],
      audience: { all: false, faculties: ['FOC'], programmes: ['BSC-SE'], years: [2] },
      priority: 'high',
      pinned: false,
      status: 'published',
      publishAt: '2026-09-19T05:00:00.000Z',
      expiresAt: '2026-09-26T18:29:59.000Z',
      startsAt: null,
      endsAt: null,
      allDay: false,
      venue: null,
      origin: 'official',
      societyId: null,
      capacity: null,
      interestedCount: 0,
      link: null,
      details: {},
      author: { uid: 'usr_acad_01', name: 'Dr. Kasun Silva', role: 'academic_staff' },
      source: { department: 'Faculty of Computing', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-09-19T04:55:00.000Z',
      updatedAt: '2026-09-19T05:00:00.000Z',
    },
    {
      id: 'cnt_evt1',
      type: 'event',
      category: 'social',
      title: "Freshers' Welcome Fair",
      summary: 'Meet societies, services and seniors.',
      body: 'Stalls from 20+ societies, free refreshments, campus tour at 11am.',
      imageUrl: null,
      tags: ['freshers', 'societies'],
      audience: { all: true, faculties: [], programmes: [], years: [] },
      priority: 'normal',
      pinned: false,
      status: 'published',
      publishAt: '2026-09-10T05:00:00.000Z',
      expiresAt: '2026-09-24T08:00:00.000Z',
      startsAt: '2026-09-24T04:00:00.000Z',
      endsAt: '2026-09-24T08:00:00.000Z',
      allDay: false,
      venue: 'Main Quad',
      origin: 'official',
      societyId: null,
      capacity: null,
      interestedCount: 86,
      link: null,
      details: {},
      author: { uid: 'usr_mgr_01', name: 'Facilities & Operations', role: 'manager' },
      source: { department: 'Student Affairs', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 2,
      createdAt: '2026-09-10T04:50:00.000Z',
      updatedAt: '2026-09-15T05:00:00.000Z',
    },
    {
      id: 'cnt_evt2',
      type: 'event',
      category: 'cultural',
      title: 'Robotics Open Build Night',
      summary: 'Hands-on build session, all welcome.',
      body: 'Bring a laptop. Kits provided.',
      imageUrl: null,
      tags: ['robotics'],
      audience: { all: true, faculties: [], programmes: [], years: [] },
      priority: 'normal',
      pinned: false,
      status: 'pending_review',
      publishAt: null,
      expiresAt: '2026-09-25T15:30:00.000Z',
      startsAt: '2026-09-25T12:00:00.000Z',
      endsAt: '2026-09-25T15:30:00.000Z',
      allDay: false,
      venue: 'Lab 2',
      origin: 'student',
      societyId: 'soc_robotics',
      capacity: 40,
      interestedCount: 0,
      link: null,
      details: {},
      author: { uid: 'usr_rep_01', name: 'Tharindu Jayasuriya', role: 'society_rep' },
      source: { department: 'Robotics Club', verified: false },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-09-19T03:00:00.000Z',
      updatedAt: '2026-09-19T03:00:00.000Z',
    },
    {
      id: 'cnt_cal01',
      type: 'calendar',
      category: 'add_drop',
      title: 'Add/Drop deadline',
      summary: 'Last day to add or drop modules without penalty.',
      body: 'Submit changes to the Registrar by 4pm.',
      imageUrl: null,
      tags: ['deadline'],
      audience: { all: true, faculties: [], programmes: [], years: [] },
      priority: 'high',
      pinned: false,
      status: 'published',
      publishAt: '2026-08-20T05:00:00.000Z',
      expiresAt: '2026-09-30T18:29:59.000Z',
      startsAt: '2026-09-29T18:30:00.000Z',
      endsAt: '2026-09-30T18:29:59.000Z',
      allDay: true,
      venue: null,
      origin: 'official',
      societyId: null,
      capacity: null,
      interestedCount: 0,
      link: null,
      details: { semester: 'S1-2026' },
      author: { uid: 'usr_admin_01', name: 'Registrar Office', role: 'admin' },
      source: { department: 'Registrar', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-08-20T04:50:00.000Z',
      updatedAt: '2026-08-20T05:00:00.000Z',
    },
    {
      id: 'cnt_dine01',
      type: 'info',
      category: 'dining',
      title: 'Canteen menu & opening hours',
      summary: 'Open 7:30 am – 5 pm on weekdays.',
      body: 'Vegetarian option available daily.',
      imageUrl: null,
      tags: ['canteen', 'food'],
      audience: { all: true, faculties: [], programmes: [], years: [] },
      priority: 'normal',
      pinned: false,
      status: 'published',
      publishAt: '2026-09-01T05:00:00.000Z',
      expiresAt: null,
      startsAt: null,
      endsAt: null,
      allDay: false,
      venue: 'Canteen, Block A',
      origin: 'official',
      societyId: null,
      capacity: null,
      interestedCount: 0,
      link: null,
      details: {
        hours: { 'mon-fri': '07:30-17:00', sat: '08:00-13:00', sun: 'closed' },
        location: 'Canteen, Block A',
        menu: [
          { day: 'mon', items: ['Rice & curry', 'Kottu', 'Veg fried rice'] },
          { day: 'tue', items: ['String hoppers', 'Fried rice'] },
        ],
      },
      author: { uid: 'usr_mgr_01', name: 'Facilities & Operations', role: 'manager' },
      source: { department: 'Facilities & Operations', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 4,
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
    {
      id: 'cnt_gl01',
      type: 'guest_lecture',
      category: 'industry_talk',
      title: 'Building AI Products in Sri Lanka',
      summary: 'Talk by Ayesha Ranatunga, CTO at XYZ.',
      body: 'Open to all faculties. Q&A follows.',
      imageUrl: null,
      tags: ['ai', 'industry'],
      audience: { all: true, faculties: [], programmes: [], years: [] },
      priority: 'normal',
      pinned: false,
      status: 'published',
      publishAt: '2026-09-15T05:00:00.000Z',
      expiresAt: '2026-09-29T09:30:00.000Z',
      startsAt: '2026-09-29T08:00:00.000Z',
      endsAt: '2026-09-29T09:30:00.000Z',
      allDay: false,
      venue: 'Auditorium',
      origin: 'official',
      societyId: null,
      capacity: 200,
      interestedCount: 34,
      link: null,
      details: { speaker: 'Ayesha Ranatunga', speakerTitle: 'CTO, XYZ', topic: 'Building AI Products in Sri Lanka' },
      author: { uid: 'usr_acad_01', name: 'Dr. Kasun Silva', role: 'academic_staff' },
      source: { department: 'Faculty of Computing', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-09-15T04:50:00.000Z',
      updatedAt: '2026-09-15T05:00:00.000Z',
    },
    {
      id: 'cnt_job01',
      type: 'opportunity',
      category: 'internship',
      title: 'Software Engineering Intern — Colombo',
      summary: '3-month paid internship, apply by 10 Oct.',
      body: 'Open to Year 3+ students in FOC/FOE.',
      imageUrl: null,
      tags: ['internship', 'software'],
      audience: { all: false, faculties: ['FOC', 'FOE'], programmes: [], years: [3, 4] },
      priority: 'normal',
      pinned: false,
      status: 'published',
      publishAt: '2026-09-16T05:00:00.000Z',
      expiresAt: '2026-10-10T18:29:59.000Z',
      startsAt: null,
      endsAt: null,
      allDay: false,
      venue: null,
      origin: 'official',
      societyId: null,
      capacity: null,
      interestedCount: 0,
      link: 'https://example.com/apply',
      details: {
        company: 'XYZ Technologies',
        location: 'Colombo',
        type: 'internship',
        deadline: '2026-10-10T18:29:59.000Z',
        applyUrl: 'https://example.com/apply',
      },
      author: { uid: 'usr_acad_01', name: 'Dr. Kasun Silva', role: 'academic_staff' },
      source: { department: 'Faculty of Computing', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-09-16T04:50:00.000Z',
      updatedAt: '2026-09-16T05:00:00.000Z',
    },
  ],

  alerts: [
    {
      id: 'alt_old01',
      kind: 'emergency',
      status: 'resolved',
      title: 'Fire drill — evacuate Block A',
      body: 'This is a drill. Proceed to the Main Quad.',
      affects: null,
      sendSms: true,
      updates: [],
      impact: { eventsFlagged: 0, bookingsCancelled: 0, usersNotified: 1800, smsSent: 1750 },
      confirmToken: null,
      createdBy: { uid: 'usr_admin_01', name: 'Registrar Office', role: 'admin' },
      confirmedBy: 'usr_admin_01',
      publishedAt: '2026-09-05T04:00:00.000Z',
      resolvedAt: '2026-09-05T04:40:00.000Z',
      lastUpdatedAt: '2026-09-05T04:40:00.000Z',
      createdAt: '2026-09-05T03:58:00.000Z',
    },
    {
      id: 'alt_9f8e7d',
      kind: 'closure',
      status: 'draft',
      title: 'Campus closed Tue 22 Sep — heavy rain',
      body: 'All lectures and labs are cancelled. Stay safe.',
      affects: {
        startsAt: '2026-09-21T18:30:00.000Z',
        endsAt: '2026-09-22T18:29:59.000Z',
        scope: 'campus',
        buildings: [],
        cancelBookings: true,
        flagEvents: true,
      },
      sendSms: true,
      updates: [],
      impact: null,
      confirmToken: 'cf_7Hk29x',
      createdBy: { uid: 'usr_admin_01', name: 'Registrar Office', role: 'admin' },
      confirmedBy: null,
      publishedAt: null,
      resolvedAt: null,
      lastUpdatedAt: '2026-09-21T11:55:00.000Z',
      createdAt: '2026-09-21T11:55:00.000Z',
    },
  ],

  societies: [
    {
      id: 'soc_robotics',
      name: 'Robotics Club',
      description: 'Build, break, repeat.',
      category: 'technology',
      logoUrl: null,
      coverUrl: null,
      contactEmail: 'robotics@ucl.demo',
      socials: { instagram: '@ucl_robotics' },
      meetingInfo: 'Fridays 5pm, Lab 2',
      joinMode: 'approval',
      presidentUid: 'usr_rep_01',
      repUids: ['usr_rep_01'],
      memberCount: 42,
      status: 'active',
      source: { department: 'Student Affairs', verified: true },
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-10T05:00:00.000Z',
    },
    {
      id: 'soc_rotaract',
      name: 'Rotaract Club',
      description: 'Service above self.',
      category: 'community',
      logoUrl: null,
      coverUrl: null,
      contactEmail: 'rotaract@ucl.demo',
      socials: {},
      meetingInfo: 'Wednesdays 4pm, Room A101',
      joinMode: 'open',
      presidentUid: null,
      repUids: [],
      memberCount: 120,
      status: 'active',
      source: { department: 'Student Affairs', verified: true },
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
  ],

  rooms: [
    {
      id: 'room_b204',
      name: 'B204 Study Room',
      building: 'Block B',
      floor: 2,
      capacity: 8,
      features: ['whiteboard', 'projector', 'ac'],
      openTime: '08:00',
      closeTime: '20:00',
      closedWeekdays: [0],
      bookable: true,
      status: 'active',
    },
    {
      id: 'room_b205',
      name: 'B205 Group Room',
      building: 'Block B',
      floor: 2,
      capacity: 6,
      features: ['whiteboard'],
      openTime: '08:00',
      closeTime: '20:00',
      closedWeekdays: [0],
      bookable: true,
      status: 'active',
    },
  ],

  bookings: [
    {
      id: 'bk_tt001',
      roomId: 'room_b204',
      roomName: 'B204 Study Room',
      uid: null,
      userName: 'Timetable',
      startsAt: '2026-09-21T03:30:00.000Z',
      endsAt: '2026-09-21T05:00:00.000Z',
      purpose: 'Tutorial — MA101',
      attendees: 0,
      status: 'confirmed',
      source: 'timetable',
      slotIds: ['room_b204_20260921T0330Z', 'room_b204_20260921T0400Z', 'room_b204_20260921T0430Z'],
      createdAt: '2026-08-01T05:00:00.000Z',
      cancelledAt: null,
      cancelReason: null,
    },
    {
      id: 'bk_5d5d',
      roomId: 'room_b204',
      roomName: 'B204 Study Room',
      uid: 'usr_student_01',
      userName: 'Nimasha P.',
      startsAt: '2026-09-21T08:30:00.000Z',
      endsAt: '2026-09-21T10:00:00.000Z',
      purpose: 'DB group study',
      attendees: 5,
      status: 'confirmed',
      source: 'student',
      slotIds: ['room_b204_20260921T0830Z', 'room_b204_20260921T0900Z', 'room_b204_20260921T0930Z'],
      createdAt: '2026-09-19T06:10:00.000Z',
      cancelledAt: null,
      cancelReason: null,
    },
  ],

  requests: [
    {
      id: 'req_l0st01',
      type: 'lost',
      status: 'open',
      visibility: 'public',
      title: 'Black Casio calculator (fx-991)',
      description: 'Lost after DB lecture.',
      imageUrls: [],
      location: 'Block B, Lecture Hall 2',
      occurredAt: '2026-09-18T07:00:00.000Z',
      data: { itemCategory: 'electronics', color: 'black', brand: 'Casio' },
      verificationHint: null,
      handoverNote: null,
      ownerUid: 'usr_student_01',
      ownerName: 'Nimasha P.',
      assigneeUid: null,
      resolution: null,
      createdAt: '2026-09-18T09:00:00.000Z',
      updatedAt: '2026-09-18T09:00:00.000Z',
      resolvedAt: null,
    },
    {
      id: 'req_f0und9',
      type: 'found',
      status: 'open',
      visibility: 'public',
      title: 'Casio calculator',
      description: 'Found on a desk.',
      imageUrls: [],
      location: 'Block B, Lecture Hall 2',
      occurredAt: '2026-09-18T09:30:00.000Z',
      data: { itemCategory: 'electronics', color: 'black', brand: 'Casio', handedTo: 'security_desk' },
      verificationHint: 'Has a small Tux sticker on the back cover',
      handoverNote: null,
      ownerUid: 'usr_student_02',
      ownerName: 'Ravi K.',
      assigneeUid: null,
      resolution: null,
      createdAt: '2026-09-18T10:00:00.000Z',
      updatedAt: '2026-09-18T10:00:00.000Z',
      resolvedAt: null,
    },
    {
      id: 'req_fac01',
      type: 'facility_issue',
      status: 'in_progress',
      visibility: 'private',
      title: 'Projector not working in LH2',
      description: 'No signal from HDMI.',
      imageUrls: [],
      location: 'Block B, LH2',
      occurredAt: null,
      data: { building: 'Block B', room: 'LH2', issueCategory: 'it', severity: 'medium' },
      verificationHint: null,
      handoverNote: null,
      ownerUid: 'usr_student_01',
      ownerName: 'Nimasha P.',
      assigneeUid: 'usr_mgr_01',
      resolution: null,
      createdAt: '2026-09-17T08:00:00.000Z',
      updatedAt: '2026-09-18T05:00:00.000Z',
      resolvedAt: null,
    },
  ],

  faqs: [
    {
      id: 'faq_01',
      question: 'How do I request a transcript?',
      answer: "Submit the transcript form at the Registrar's counter (Admin Block, Room 3). Processing takes 3 working days.",
      category: 'academic',
      keywords: ['transcript', 'records', 'registrar'],
      order: 1,
      status: 'published',
      helpfulCount: 12,
      unhelpfulCount: 1,
      source: { department: 'Registrar', verified: true },
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
    {
      id: 'faq_02',
      question: 'What should I do if I lose my student ID card?',
      answer: 'Report it at the Security Desk and pay the LKR 500 replacement fee at Finance.',
      category: 'general',
      keywords: ['id card', 'lost', 'replacement'],
      order: 2,
      status: 'published',
      helpfulCount: 8,
      unhelpfulCount: 0,
      source: { department: 'Student Affairs', verified: true },
      updatedAt: '2026-08-25T05:00:00.000Z',
    },
  ],

  staff: [
    {
      id: 'stf_01',
      name: 'Ms. Dilani Fernando',
      title: 'Student Counsellor',
      department: 'Student Wellbeing',
      email: 'counsellor@ucl.demo',
      phone: '+94112223344',
      office: 'Admin Block, Room 12',
      officeHours: 'Mon–Fri 9:00–16:00',
      topics: ['counselling', 'wellbeing', 'stress'],
      status: 'active',
    },
    {
      id: 'stf_02',
      name: 'Mr. Chamara Wickrama',
      title: 'IT Helpdesk Lead',
      department: 'IT Services',
      email: 'helpdesk@ucl.demo',
      phone: '+94112223355',
      office: 'Block A, Ground Floor',
      officeHours: 'Mon–Fri 8:30–17:00',
      topics: ['wifi', 'email', 'password', 'software'],
      status: 'active',
    },
  ],

  notifications: [
    {
      id: 'ntf_001',
      uid: 'usr_student_01',
      type: 'announcement',
      title: 'Database Systems lab moved to Lab 3',
      body: 'From Monday, DB labs for Year 2 SE run in Lab 3.',
      refType: 'content',
      refId: 'cnt_a1b2c3',
      channels: ['inbox', 'push'],
      readAt: null,
      createdAt: '2026-09-19T05:00:05.000Z',
    },
    {
      id: 'ntf_002',
      uid: 'usr_student_01',
      type: 'request',
      title: 'Possible match for your lost item',
      body: "A found 'Casio calculator' was reported at Block B.",
      refType: 'request',
      refId: 'req_f0und9',
      channels: ['inbox', 'push'],
      readAt: null,
      createdAt: '2026-09-18T10:00:10.000Z',
    },
  ],
};

/**
 * Executes idempotent database seeding using Admin SDK
 */
export async function runDatabaseSeed(): Promise<void> {
  console.log('🚀 Starting authoritative backend database seed (idempotent)...');

  // 1. Seed Auth users and custom claims
  for (const account of SEED_DATA.demoAccounts) {
    try {
      let userRecord: admin.auth.UserRecord;
      try {
        userRecord = await auth.getUser(account.uid);
      } catch {
        userRecord = await auth.createUser({
          uid: account.uid,
          email: account.email,
          displayName: account.displayName,
          password: 'Demo@1234',
        });
      }
      // Assign custom claim
      await auth.setCustomUserClaims(account.uid, { role: account.role });
      console.log(`✓ Auth user & custom claim set for ${account.uid} (${account.role})`);
    } catch (err: any) {
      console.warn(`Auth user error for ${account.uid}:`, err.message);
    }
  }

  // Helper to batch set collection
  const setCollection = async (collectionName: string, items: Array<{ id: string; [key: string]: any }>) => {
    const batch = db.batch();
    for (const item of items) {
      const ref = db.collection(collectionName).doc(item.id);
      batch.set(ref, item, { merge: true });
    }
    await batch.commit();
    console.log(`✓ Seeded ${items.length} records into '${collectionName}'`);
  };

  await setCollection('users', SEED_DATA.users);
  await setCollection('contents', SEED_DATA.contents);
  await setCollection('alerts', SEED_DATA.alerts);
  await setCollection('societies', SEED_DATA.societies);
  await setCollection('rooms', SEED_DATA.rooms);
  await setCollection('bookings', SEED_DATA.bookings);
  await setCollection('requests', SEED_DATA.requests);
  await setCollection('faqs', SEED_DATA.faqs);
  await setCollection('staff', SEED_DATA.staff);
  await setCollection('notifications', SEED_DATA.notifications);

  // Seed initial roomSlot locks for booked slots
  const slotBatch = db.batch();
  for (const booking of SEED_DATA.bookings) {
    for (const slotId of booking.slotIds) {
      const slotRef = db.collection('roomSlots').doc(slotId);
      slotBatch.set(slotRef, {
        id: slotId,
        roomId: booking.roomId,
        bookingId: booking.id,
        slotStartUtc: booking.startsAt,
      }, { merge: true });
    }
  }
  await slotBatch.commit();
  console.log('✓ Seeded roomSlots lock documents');

  console.log('🎉 Database seed completed successfully!');
}

// Allow direct execution if run via CLI
if (require.main === module) {
  runDatabaseSeed()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Seed failure:', err);
      process.exit(1);
    });
}
