/**
 * Extended Seed Script — Frontend Development Data Pack
 * Adds richer demo data across all collections so frontend devs
 * can immediately test screens without needing real user input.
 *
 * Collections seeded:
 *   users (9), contents (7+5=12), alerts (1 active), societies (2+3=5),
 *   rooms (2+2=4), bookings (2+3=5), requests (3+5=8), faqs (2+6=8),
 *   staff (2+4=6), notifications (2+6=8), societyMembers (viewer membership)
 *
 * Run: GCLOUD_PROJECT=ucl-net-prod node lib/scripts/seed_extended.js
 */
import * as admin from 'firebase-admin';

if (admin.apps.length === 0) {
  admin.initializeApp();
}

const db = admin.firestore();

async function batchSet(col: string, docs: Array<{ id: string; [k: string]: any }>) {
  const batch = db.batch();
  for (const d of docs) {
    batch.set(db.collection(col).doc(d.id), d, { merge: true });
  }
  await batch.commit();
  console.log(`✓ Extended seed: ${docs.length} → '${col}'`);
}

async function run() {
  console.log('🌱 Running extended frontend seed...');

  // ── Additional Contents (published events, announcements, opportunities) ──
  await batchSet('contents', [
    {
      id: 'cnt_ann01',
      type: 'announcement',
      category: 'finance',
      title: 'Merit Scholarship Applications Open',
      summary: 'Apply for the UCL Merit Scholarship by 30 Sep. Open to all Year 2+ students.',
      body: 'The UCL Merit Scholarship (Rs. 50,000) is open to full-time students with a GPA ≥ 3.5. Submit via the Finance Office by **30 September 2026**.',
      imageUrl: null,
      tags: ['scholarship', 'finance', 'merit'],
      audience: { all: true, faculties: [], programmes: [], years: [] },
      priority: 'high',
      pinned: true,
      status: 'published',
      publishAt: '2026-09-18T05:00:00.000Z',
      expiresAt: '2026-09-30T18:29:59.000Z',
      startsAt: null, endsAt: null, allDay: false, venue: null,
      origin: 'official', societyId: null, capacity: null, interestedCount: 0, link: null,
      details: { deadline: '2026-09-30T18:29:59.000Z', amount: 50000, currency: 'LKR' },
      author: { uid: 'usr_fin_01', name: 'Dilini Perera', role: 'finance_staff' },
      source: { department: 'Finance Office', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-09-18T04:50:00.000Z',
      updatedAt: '2026-09-18T05:00:00.000Z',
    },
    {
      id: 'cnt_ann02',
      type: 'announcement',
      category: 'academic',
      title: 'Mid-Semester Exam Timetable Released',
      summary: 'Check your exam schedule for October on the student portal.',
      body: '## Mid-Semester Examinations\n\n| Programme | Date | Time | Venue |\n|---|---|---|---|\n| BSC-SE (Year 2) | 10 Oct | 9:00 AM | Hall A |\n| BBA (Year 1) | 11 Oct | 9:00 AM | Hall B |\n\nBring your **student ID** and arrive 15 minutes early.',
      imageUrl: null,
      tags: ['exam', 'timetable', 'mid-semester'],
      audience: { all: true, faculties: [], programmes: [], years: [] },
      priority: 'high',
      pinned: false,
      status: 'published',
      publishAt: '2026-09-17T05:00:00.000Z',
      expiresAt: '2026-10-12T18:29:59.000Z',
      startsAt: null, endsAt: null, allDay: false, venue: null,
      origin: 'official', societyId: null, capacity: null, interestedCount: 0, link: null,
      details: {},
      author: { uid: 'usr_admin_01', name: 'Registrar Office', role: 'admin' },
      source: { department: 'Academic Registry', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-09-17T04:50:00.000Z',
      updatedAt: '2026-09-17T05:00:00.000Z',
    },
    {
      id: 'cnt_evt3',
      type: 'event',
      category: 'academic',
      title: 'Career Fair 2026',
      summary: 'Meet 30+ top employers. All students welcome.',
      body: 'Dress professionally. Bring CVs. Companies include: WSO2, 99X, Sysco Labs, Dialog Axiata, Hayleys and more.',
      imageUrl: null,
      tags: ['career', 'job', 'internship'],
      audience: { all: true, faculties: [], programmes: [], years: [] },
      priority: 'high',
      pinned: true,
      status: 'published',
      publishAt: '2026-09-15T05:00:00.000Z',
      expiresAt: '2026-10-01T10:00:00.000Z',
      startsAt: '2026-10-01T04:00:00.000Z',
      endsAt: '2026-10-01T10:00:00.000Z',
      allDay: false,
      venue: 'Main Hall, Block A',
      origin: 'official', societyId: null, capacity: 500, interestedCount: 234, link: null,
      details: { registrationUrl: 'https://ucl.demo/career-fair', employers: 30 },
      author: { uid: 'usr_mgr_01', name: 'Facilities Manager', role: 'manager' },
      source: { department: 'Student Affairs', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-09-15T04:50:00.000Z',
      updatedAt: '2026-09-15T05:00:00.000Z',
    },
    {
      id: 'cnt_evt4',
      type: 'event',
      category: 'sports',
      title: 'Inter-Faculty Cricket Tournament',
      summary: 'FOC vs FOE vs FOB. Final on 28 Sep at the main ground.',
      body: 'Cheer for your faculty! Gates open at 8:30 AM. Free entry for all UCL students with ID.',
      imageUrl: null,
      tags: ['cricket', 'sports', 'inter-faculty'],
      audience: { all: true, faculties: [], programmes: [], years: [] },
      priority: 'normal',
      pinned: false,
      status: 'published',
      publishAt: '2026-09-19T05:00:00.000Z',
      expiresAt: '2026-09-28T16:00:00.000Z',
      startsAt: '2026-09-28T03:30:00.000Z',
      endsAt: '2026-09-28T12:00:00.000Z',
      allDay: false,
      venue: 'UCL Main Cricket Ground',
      origin: 'official', societyId: null, capacity: 800, interestedCount: 412, link: null,
      details: {},
      author: { uid: 'usr_mgr_01', name: 'Facilities Manager', role: 'manager' },
      source: { department: 'Student Affairs', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-09-19T04:50:00.000Z',
      updatedAt: '2026-09-19T05:00:00.000Z',
    },
    {
      id: 'cnt_evt5',
      type: 'guest_lecture',
      category: 'academic',
      title: 'DevOps in Practice — with WSO2 Engineers',
      summary: 'Live session on CI/CD, containers and cloud-native development.',
      body: 'Join WSO2 engineering leads for an interactive walkthrough of real-world DevOps pipelines. Q&A included.',
      imageUrl: null,
      tags: ['devops', 'tech', 'wso2', 'cicd'],
      audience: { all: false, faculties: ['FOC', 'FOE'], programmes: [], years: [] },
      priority: 'high',
      pinned: false,
      status: 'published',
      publishAt: '2026-09-19T05:00:00.000Z',
      expiresAt: '2026-09-26T12:00:00.000Z',
      startsAt: '2026-09-26T08:00:00.000Z',
      endsAt: '2026-09-26T10:30:00.000Z',
      allDay: false,
      venue: 'Auditorium, Block A',
      origin: 'official', societyId: null, capacity: 150, interestedCount: 78, link: null,
      details: { speaker: 'WSO2 Engineering Team', topic: 'DevOps in Practice', registrationRequired: false },
      author: { uid: 'usr_acad_01', name: 'Dr. Kasun Silva', role: 'academic_staff' },
      source: { department: 'Faculty of Computing', verified: true },
      flags: { affectedByAlertId: null },
      review: { reviewedBy: null, reviewedAt: null, reason: null },
      version: 1,
      createdAt: '2026-09-19T04:50:00.000Z',
      updatedAt: '2026-09-19T05:00:00.000Z',
    },
  ]);

  // ── One ACTIVE Alert for demo ──
  await batchSet('alerts', [
    {
      id: 'alt_active01',
      kind: 'schedule_change',
      status: 'active',
      title: 'Water Supply Disruption — Block C Labs',
      body: 'Water supply to Block C labs is interrupted until 3 PM today. Use Block A facilities.',
      affects: null,
      sendSms: false,
      updates: [{ body: 'Repair team is on-site.', createdAt: '2026-09-19T07:30:00.000Z' }],
      impact: { eventsFlagged: 0, bookingsCancelled: 0, usersNotified: 400, smsSent: 0 },
      confirmToken: null,
      createdBy: { uid: 'usr_mgr_01', name: 'Facilities Manager', role: 'manager' },
      confirmedBy: 'usr_mgr_01',
      publishedAt: '2026-09-19T07:00:00.000Z',
      resolvedAt: null,
      lastUpdatedAt: '2026-09-19T07:30:00.000Z',
      createdAt: '2026-09-19T06:58:00.000Z',
    },
  ]);

  // ── Additional Societies ──
  await batchSet('societies', [
    {
      id: 'soc_debating',
      name: 'Debating Society',
      description: 'Sharpen your arguments. UCL Debate team champions, 3 years running.',
      category: 'academic',
      logoUrl: null,
      coverUrl: null,
      contactEmail: 'debating@ucl.demo',
      socials: { instagram: '@ucl_debate', facebook: 'UCLDebate' },
      meetingInfo: 'Tuesdays 5pm, Room A205',
      joinMode: 'open',
      presidentUid: null,
      repUids: [],
      memberCount: 65,
      status: 'active',
      source: { department: 'Student Affairs', verified: true },
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-10T05:00:00.000Z',
    },
    {
      id: 'soc_photography',
      name: 'Photography Club',
      description: 'Capturing UCL life, one shot at a time.',
      category: 'arts',
      logoUrl: null,
      coverUrl: null,
      contactEmail: 'photo@ucl.demo',
      socials: { instagram: '@ucl_photo' },
      meetingInfo: 'Thursdays 4pm, Room C108',
      joinMode: 'open',
      presidentUid: null,
      repUids: [],
      memberCount: 89,
      status: 'active',
      source: { department: 'Student Affairs', verified: true },
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-10T05:00:00.000Z',
    },
    {
      id: 'soc_ieee',
      name: 'IEEE Student Branch',
      description: 'Advancing technology for humanity.',
      category: 'technology',
      logoUrl: null,
      coverUrl: null,
      contactEmail: 'ieee@ucl.demo',
      socials: { linkedin: 'ucl-ieee' },
      meetingInfo: 'Monthly general meetings',
      joinMode: 'approval',
      presidentUid: null,
      repUids: [],
      memberCount: 200,
      status: 'active',
      source: { department: 'Faculty of Engineering', verified: true },
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-10T05:00:00.000Z',
    },
  ]);

  // ── Viewer's society membership (Nimasha is in Robotics Club) ──
  await batchSet('societyMembers', [
    {
      id: 'usr_student_01_soc_robotics',
      uid: 'usr_student_01',
      societyId: 'soc_robotics',
      status: 'approved',
      joinedAt: '2026-08-15T05:00:00.000Z',
    },
  ]);

  // ── Additional Rooms ──
  await batchSet('rooms', [
    {
      id: 'room_a101',
      name: 'A101 Lecture Room',
      building: 'Block A',
      floor: 1,
      capacity: 80,
      features: ['projector', 'ac', 'whiteboard', 'microphone'],
      openTime: '07:30',
      closeTime: '21:00',
      status: 'active',
      bookableByRoles: ['student', 'academic_staff', 'society_rep'],
      notes: 'Lecture-style seating. Request approval for society events.',
    },
    {
      id: 'room_c205',
      name: 'C205 Computer Lab',
      building: 'Block C',
      floor: 2,
      capacity: 30,
      features: ['computers', 'projector', 'ac'],
      openTime: '08:00',
      closeTime: '20:00',
      status: 'active',
      bookableByRoles: ['academic_staff', 'super_admin', 'admin'],
      notes: '30 workstations. Bookable by staff only.',
    },
  ]);

  // ── Additional Requests (Lost & Found + facility issues) ──
  await batchSet('requests', [
    {
      id: 'req_lost02',
      type: 'lost',
      title: 'Lost blue water bottle — Canteen area',
      description: 'Stainless steel blue bottle, "NP" initials stickered on it. Lost during lunch on 18 Sep.',
      category: 'personal_item',
      imageUrl: null,
      location: 'Canteen / Level 1',
      lostAt: '2026-09-18T07:00:00.000Z',
      status: 'open',
      visibility: 'public',
      ownerUid: 'usr_student_01',
      verificationHint: null,
      handoverNote: null,
      resolvedBy: null,
      resolvedAt: null,
      createdAt: '2026-09-18T09:00:00.000Z',
      updatedAt: '2026-09-18T09:00:00.000Z',
    },
    {
      id: 'req_found01',
      type: 'found',
      title: 'Found calculator in Library — scientific',
      description: 'Casio FX-991 found on Study Table 3, Library Level 2.',
      category: 'personal_item',
      imageUrl: null,
      location: 'Library, Level 2, Table 3',
      lostAt: '2026-09-19T03:30:00.000Z',
      status: 'open',
      visibility: 'public',
      ownerUid: 'usr_student_02',
      verificationHint: 'What model is the calculator? What name is on the case?',
      handoverNote: null,
      resolvedBy: null,
      resolvedAt: null,
      createdAt: '2026-09-19T05:00:00.000Z',
      updatedAt: '2026-09-19T05:00:00.000Z',
    },
    {
      id: 'req_facility01',
      type: 'facility_issue',
      title: 'Projector not working in Room B204',
      description: 'Projector in B204 shows a no-signal error. Reported during 10AM lecture.',
      category: 'equipment',
      imageUrl: null,
      location: 'Room B204, Block B',
      lostAt: null,
      status: 'in_progress',
      visibility: 'public',
      ownerUid: 'usr_acad_01',
      verificationHint: null,
      handoverNote: 'Maintenance dispatched.',
      resolvedBy: null,
      resolvedAt: null,
      createdAt: '2026-09-19T04:30:00.000Z',
      updatedAt: '2026-09-19T06:00:00.000Z',
    },
    {
      id: 'req_feedback01',
      type: 'feedback',
      title: 'Canteen queue too long during lunch',
      description: 'The 12:30–1:30 PM slot has very long queues. Suggest staggering lunch breaks per faculty.',
      category: null,
      imageUrl: null,
      location: 'Canteen',
      lostAt: null,
      status: 'open',
      visibility: 'public',
      ownerUid: 'usr_student_02',
      verificationHint: null,
      handoverNote: null,
      resolvedBy: null,
      resolvedAt: null,
      createdAt: '2026-09-18T08:30:00.000Z',
      updatedAt: '2026-09-18T08:30:00.000Z',
    },
    {
      id: 'req_textbook01',
      type: 'textbook',
      title: 'Looking to borrow: Clean Code by Robert Martin',
      description: 'Need for 2 weeks for Software Engineering module. Will return in good condition.',
      category: 'textbook',
      imageUrl: null,
      location: null,
      lostAt: null,
      status: 'open',
      visibility: 'public',
      ownerUid: 'usr_student_01',
      verificationHint: null,
      handoverNote: null,
      resolvedBy: null,
      resolvedAt: null,
      createdAt: '2026-09-17T08:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
  ]);

  // ── Additional FAQs ──
  await batchSet('faqs', [
    {
      id: 'faq_003',
      category: 'academic',
      question: 'How do I apply for a grade appeal?',
      answer: 'Submit a Grade Appeal Form at the Registrar\'s Office within 14 days of results publication. You will need your student ID and a written reason for the appeal. Decisions are communicated within 21 working days.',
      tags: ['grade', 'appeal', 'results', 'exam'],
      helpfulCount: 87,
      notHelpfulCount: 3,
      source: { department: 'Academic Registry', verified: true },
      authorUid: 'usr_admin_01',
      status: 'published',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
    {
      id: 'faq_004',
      category: 'facilities',
      question: 'How do I book a study room?',
      answer: 'Open the UCL Campus App, go to **Room Bookings**, select your desired date and room, then confirm. Bookings are limited to 2 hours at a time and a maximum of 2 concurrent active bookings per student.',
      tags: ['room', 'booking', 'study', 'facilities'],
      helpfulCount: 142,
      notHelpfulCount: 8,
      source: { department: 'Facilities', verified: true },
      authorUid: 'usr_mgr_01',
      status: 'published',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-10T05:00:00.000Z',
    },
    {
      id: 'faq_005',
      category: 'finance',
      question: 'What are the tuition fee payment deadlines?',
      answer: 'Semester 1 fees are due by **15 October 2026**. A 5% late fee is charged after this date. Payment can be made online via the Finance Portal or at the Finance Office (Block A, Ground Floor) between 8:30 AM–4:30 PM weekdays.',
      tags: ['fees', 'tuition', 'payment', 'deadline', 'finance'],
      helpfulCount: 203,
      notHelpfulCount: 5,
      source: { department: 'Finance Office', verified: true },
      authorUid: 'usr_fin_01',
      status: 'published',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-10T05:00:00.000Z',
    },
    {
      id: 'faq_006',
      category: 'general',
      question: 'What are the library hours?',
      answer: 'The UCL Library is open **Monday–Friday 8 AM–10 PM**, Saturday **9 AM–6 PM**, and closed on Sundays and public holidays. Extended hours are available during examination periods.',
      tags: ['library', 'hours', 'opening times'],
      helpfulCount: 310,
      notHelpfulCount: 2,
      source: { department: 'Library Services', verified: true },
      authorUid: 'usr_admin_01',
      status: 'published',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
    {
      id: 'faq_007',
      category: 'academic',
      question: 'How do I get an official transcript?',
      answer: 'Apply for transcripts at the Registrar\'s Office or via the Student Portal. Processing takes **5–7 working days**. An official sealed transcript costs Rs. 500. Unofficial transcripts can be downloaded from the portal immediately.',
      tags: ['transcript', 'document', 'registrar', 'official'],
      helpfulCount: 95,
      notHelpfulCount: 1,
      source: { department: 'Academic Registry', verified: true },
      authorUid: 'usr_admin_01',
      status: 'published',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
    {
      id: 'faq_008',
      category: 'societies',
      question: 'How do I start a new society?',
      answer: 'Submit a Society Registration Form to the Student Affairs Office with at least 15 founding members, a constitution, and a faculty advisor. The approval process takes up to 30 days. Approved societies get a budget allocation and official representation.',
      tags: ['society', 'club', 'registration', 'new'],
      helpfulCount: 44,
      notHelpfulCount: 4,
      source: { department: 'Student Affairs', verified: true },
      authorUid: 'usr_mgr_01',
      status: 'published',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
  ]);

  // ── Additional Staff ──
  await batchSet('staff', [
    {
      id: 'stf_002',
      uid: 'usr_fin_01',
      displayName: 'Dilini Perera',
      title: 'Senior Finance Officer',
      department: 'Finance Office',
      faculty: null,
      email: 'finance@ucl.demo',
      phone: '+94776665544',
      officeLocation: 'Block A, Ground Floor, Room A003',
      officeHours: 'Mon–Fri: 8:30 AM–4:30 PM',
      photoUrl: null,
      specializations: ['student fees', 'scholarships', 'financial aid'],
      status: 'active',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
    {
      id: 'stf_003',
      uid: 'usr_mgr_01',
      displayName: 'Facilities Manager',
      title: 'Campus Operations Manager',
      department: 'Facilities & Operations',
      faculty: null,
      email: 'manager@ucl.demo',
      phone: '+94774443322',
      officeLocation: 'Block B, Level 1, Room B101',
      officeHours: 'Mon–Fri: 8:00 AM–5:00 PM',
      photoUrl: null,
      specializations: ['room bookings', 'maintenance', 'campus events'],
      status: 'active',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
    {
      id: 'stf_004',
      uid: null,
      displayName: 'Prof. Nimal Bandara',
      title: 'Senior Lecturer — FOE',
      department: 'Faculty of Engineering',
      faculty: 'FOE',
      email: 'nimal.bandara@ucl.demo',
      phone: '+94771112233',
      officeLocation: 'Block D, Level 3, Room D310',
      officeHours: 'Mon, Wed, Fri: 2:00 PM–4:00 PM',
      photoUrl: null,
      specializations: ['electrical engineering', 'power systems', 'IoT'],
      status: 'active',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
    {
      id: 'stf_005',
      uid: null,
      displayName: 'Dr. Shamali Fernando',
      title: 'Lecturer — FOB',
      department: 'Faculty of Business',
      faculty: 'FOB',
      email: 'shamali.fernando@ucl.demo',
      phone: '+94772223311',
      officeLocation: 'Block E, Level 2, Room E210',
      officeHours: 'Tue, Thu: 10:00 AM–12:00 PM',
      photoUrl: null,
      specializations: ['marketing', 'consumer behavior', 'brand strategy'],
      status: 'active',
      createdAt: '2026-08-01T05:00:00.000Z',
      updatedAt: '2026-09-01T05:00:00.000Z',
    },
  ]);

  // ── Richer Notifications for student inbox ──
  await batchSet('notifications', [
    {
      id: 'ntf_ext01',
      uid: 'usr_student_01',
      type: 'announcement',
      title: 'Merit Scholarship Applications Open',
      body: 'Apply for the UCL Merit Scholarship by 30 Sep. GPA 3.5+ required.',
      refType: 'content',
      refId: 'cnt_ann01',
      channels: ['inbox', 'push'],
      readAt: null,
      createdAt: '2026-09-18T05:00:00.000Z',
    },
    {
      id: 'ntf_ext02',
      uid: 'usr_student_01',
      type: 'event',
      title: 'Reminder: Career Fair 2026 — Tomorrow',
      body: 'The Career Fair is tomorrow at Main Hall. Bring your CV!',
      refType: 'content',
      refId: 'cnt_evt3',
      channels: ['inbox', 'push'],
      readAt: null,
      createdAt: '2026-09-30T05:00:00.000Z',
    },
    {
      id: 'ntf_ext03',
      uid: 'usr_student_01',
      type: 'alert',
      title: '[ALERT] Water Supply Disruption — Block C',
      body: 'Water supply to Block C labs is interrupted until 3 PM today.',
      refType: 'alert',
      refId: 'alt_active01',
      channels: ['inbox', 'push'],
      readAt: null,
      createdAt: '2026-09-19T07:00:00.000Z',
    },
    {
      id: 'ntf_ext04',
      uid: 'usr_student_01',
      type: 'society',
      title: 'Robotics Club: Build Night this Friday',
      body: 'Don\'t forget the Robotics Open Build Night on Sep 25, Lab 2, 5 PM.',
      refType: 'content',
      refId: 'cnt_evt2',
      channels: ['inbox'],
      readAt: '2026-09-20T06:00:00.000Z',
      createdAt: '2026-09-20T05:00:00.000Z',
    },
    {
      id: 'ntf_ext05',
      uid: 'usr_student_01',
      type: 'booking',
      title: 'Room Booking Confirmed — B204',
      body: 'Your booking for B204 Study Room on Sep 23 10:00–12:00 is confirmed.',
      refType: 'booking',
      refId: 'bk_sample1',
      channels: ['inbox', 'push'],
      readAt: '2026-09-20T10:00:00.000Z',
      createdAt: '2026-09-20T09:00:00.000Z',
    },
    {
      id: 'ntf_ext06',
      uid: 'usr_student_01',
      type: 'announcement',
      title: 'Mid-Semester Exam Timetable Released',
      body: 'Check your exam schedule for October. BSC-SE: 10 Oct, 9 AM.',
      refType: 'content',
      refId: 'cnt_ann02',
      channels: ['inbox'],
      readAt: null,
      createdAt: '2026-09-17T05:00:00.000Z',
    },
  ]);

  console.log('\n🎉 Extended frontend seed completed successfully!');
  console.log('\nCollections seeded:');
  console.log('  ✓ contents: +5 (total ~12)');
  console.log('  ✓ alerts: +1 active (total 3)');
  console.log('  ✓ societies: +3 (total 5)');
  console.log('  ✓ societyMembers: +1 (Nimasha in Robotics)');
  console.log('  ✓ rooms: +2 (total 4)');
  console.log('  ✓ requests: +5 (total 8)');
  console.log('  ✓ faqs: +6 (total 8)');
  console.log('  ✓ staff: +4 (total 6)');
  console.log('  ✓ notifications: +6 (total 8 for Nimasha)');
}

run()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('Extended seed error:', err);
    process.exit(1);
  });
